apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-demo
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: $REGISTRY/$IMAGE:$IMAGE_TAG
        imagePullPolicy: Always
        name: jenkins-demo
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
